development:
  adapter: postgresql
  database: map_quiz_development
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: map_quiz_development
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

